Pizzas/urls.py
from django.urls import path

from . import views

app_name = 'Pizzas'

urlpatterns = [
    path('', views.index, name='index'),
    path('pizzas',views.pizzas,name='pizzas'),
    path('pizzas/<int:pizza_id>/',views.pizza,name='pizza'),
    path('comment/<int:pizza_id>/',views.comment,name='comment'),
]

Pizzeria/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Pizzas.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Pizzas/models.py
from django.db import models

# Create your models here.
class Pizza(models.Model):
    pizza_name = models.CharField(max_length=100)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.pizza_name

class Topping(models.Model):
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    topping_name = models.CharField(max_length=100)

    def __str__(self):
        return self.topping_name

class Comment(models.Model):
    pizza = models.ForeignKey(Pizza, related_name='details', on_delete=models.CASCADE)
    text = models.TextField(max_length=100)

    def __str__(self):
        return self.text

class Image(models.Model):
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='images/')

Pizzas/forms.py
from django import forms
from .models import *

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']
        labels = {'text':''}

        widgets = {'text': forms.Textarea(attrs={'cols':80})}

Pizzas/views.py
from django.shortcuts import render, redirect
from .models import *
from .forms import *

# Create your views here.
def index(request):
    return render(request, "Pizzas/index.html")

def pizzas(request):
    pizzas = Pizza.objects.order_by('pizza_name')

    context = {'allpizzas': pizzas}
    return render(request, 'Pizzas/pizzas.html', context)

def pizza(request,pizza_id):
    p = Pizza.objects.get(id=pizza_id)
    toppings = Topping.objects.filter(pizza=p)
    addcomment = Comment.objects.filter(pizza=pizza_id)
    image = Image.objects.filter(pizza=pizza_id)

    context = {'pizza':p, 'toppings':toppings, 'addcomment':addcomment, 'image':image}
    return render(request, 'Pizzas/pizza.html', context)
    '''
    p= Pizza.objects.get(id=pizza_id)
    toppings = Topping.objects.filter(pizza_name=pizza_name)
    addcomment = Comment.objects.filter(pizza_name=pizza_name)
    image = Image.objects.filter(pizza_name=pizza_name_id)

    context = {'pizza_name':pizza_name, 'toppings':toppings, 'addcomment':addcomment, 'image':image}
    return render(request, 'Pizzas/pizza.html', context)
'''
def comment(request, pizza_id):
    pizza = Pizza.objects.get(id=pizza_id)
    if request.method != 'POST':
        form = CommentForm()
    else:
        form = CommentForm(data=request.POST)
        if form.is_valid():
            comment=form.save(commit=False)
            comment.pizza = pizza
            comment.save()
            return redirect('Pizzas:pizza',pizza_id=pizza_id)

    context = {'form':form,'pizza':pizza}
    return render(request, 'Pizzas/comment.html', context)

Pizzas/templates/pizzas/base.html
<p>
    <a href="{% url 'Pizzas:index' %}">Home</a>
    <a href="{% url 'Pizzas:pizzas' %}"> Browse Pizza List </a>
</p>

{% block content %}

{% endblock content %}

Pizzas/templates/pizzas/comment.html
{% extends "Pizzas/base.html" %}

{% block content %}

{% load static %}

<link rel="stylesheet" href="{% static 'format2.css' %}">

<p><a href= "{% url 'Pizzas:pizza' pizza.id %}"> {{pizza}} </a></p>

<p>What would you like to tell us?:</p>

<form action= "{% url 'Pizzas:comment' pizza.id %}" method="post">
    {% csrf_token %}

    {{form.as_p}}

    <button name="submit">Submit</button>
</form>

{% endblock content %}

Pizzas/templates/pizzas/index.html
{% extends "Pizzas/base.html" %}

{% block content %}

{% load static %}

<link rel="stylesheet" href="{% static 'format.css' %}">

<h1><p style="font-size:40px">Nates Famous Pizza</p></h1>

<p> Born in the Canadian Backwoods, raised in the Heart of Texas, you already know we have the best Pineapple Pizzas </p>
<p> The best pizzas come from a culmination of different cultures, and thats what we provide! </p>

<img src="{% static 'PepPiz.jpg' %}" style="max-height:350px"><img src="{% static 'veg.jpg' %}" style="max-height:400px;px"><img src="{% static 'pineapplepp.jpg' %}" style="max-height:400px">


{% endblock content %}

Pizzas/templates/pizzas/pizza.html
{% extends "Pizzas/base.html" %}

{% block content %}

<p>Pizza: {{ pizza }} </p>
{% for i in image %}
<div class="col-md-4">
    <img src="{{  i.image.url  }}" class="img-responsive" style="width: 40%; margin-right: 10px;" />
</div>
{% empty %}
<p> There isn't an image for this pizza yet </p>
{% endfor %}   

<form method="POST">
    <ul>
        {% for t in toppings %}

        <p>-- {{ t.topping_name}} </p>

        {% endfor %}

    </ul>
    <br><br> 
    <p>Customers said this about the {{pizza}} Pizza:</p>
    <br>   
    <ul>
        {% for c in addcomment %}
        <p>-- {{ c.text }} </p>

        {% empty %}
        <p> There are no reviews yet.</p>
        {% endfor %}
        
    </ul>

    <p><a href="{% url 'Pizzas:comment' pizza.id %}">What would you like to tell us?</a></p>
</form>
{% endblock content %}

Pizzas/templates/pizzas/pizzas.html
{% extends "Pizzas/base.html" %}

{% block content %}



<p>THE Pizza List</p>

<ul>
    {% for p in allpizzas %}

    <li>
        <a href="{% url 'Pizzas:pizza' p.id %}"> {{ p }}</a>
    </li>
    {% endfor %}
</ul>

{% endblock content %}